name: Build artifacts and create release

permissions:
  contents: write

on:
  push:
    tags:
      - 1.*

  workflow_dispatch:

jobs:
  build-pyinstaller:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - run: pip install . pyinstaller
    - run: pyinstaller pyinstaller/autotorrent.spec
    - run: cd dist && tar -czvf ../pyinstaller-macos.tar.gz *
      if: ${{ matrix.os == 'macos-latest' }}
    - run: cd dist && tar -czvf ../pyinstaller-linux.tar.gz *
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - run: cd dist && 7z a ../pyinstaller-windows.zip *
      if: ${{ matrix.os == 'windows-latest' }}
    - uses: actions/upload-artifact@v4
      with:
        name: pyinstaller-${{ matrix.os }}
        path: pyinstaller-*.*

  build-shiv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - run: pip install shiv
    - run: mkdir dist
    - run: shiv -c at2 -o dist/at2.pyz autotorrent2
    - uses: actions/upload-artifact@v4
      with:
        name: zipapp-shiv
        path: dist/at2.pyz

  create-release:
    runs-on: ubuntu-latest
    needs: [build-pyinstaller, build-shiv]
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: TODO
          files: |
            at2.pyz
            pyinstaller-linux.tar.gz
            pyinstaller-macos.tar.gz
            pyinstaller-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}